import Head from "next/head";
import styles from "../styles/Home.module.css";
import Register from "./register";
import Fueling from "./fueling";
import { Tabs, TabList, Tab, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="card text-center mt-3">
      <div className="card-body">
        <Tabs>
          <TabList>
            <Tab id="register">Register</Tab>
            <Tab id="fueling">Fueling</Tab>
          </TabList>
          <TabPanel tabId="register">
            <Register />
          </TabPanel>
          <TabPanel tabId="fueling">
            <Fueling />
          </TabPanel>
        </Tabs>
      </div>
      </div>
    </div>
  );
}
